"""increase password_hash length

Revision ID: 315a2ae47f3b
Revises: 1dd6713a4497
Create Date: 2025-04-07 18:14:26.453042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315a2ae47f3b'
down_revision = '1dd6713a4497'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
