"""Added pensioner_number field

Revision ID: fc316e1f6c52
Revises: 315a2ae47f3b
Create Date: 2025-04-07 19:25:02.915094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc316e1f6c52'
down_revision = '315a2ae47f3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pensioner_number', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['pensioner_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pensioner_number')

    # ### end Alembic commands ###
